<?php
/**
 * FulcrumOS (v10.4) - Kurulum Sihirbazı (v9.3)
 */

// --- GÜVENLİK KİLİDİ ---
if (file_exists(__DIR__ . '/install.locked')) {
    die("Kurulum zaten tamamlanmış. Güvenlik nedeniyle bu betik kilitlendi.");
}

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;

function render_header($title) {
    echo "<!DOCTYPE html>
<html lang='tr'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>FulcrumOS Kurulum - $title</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background-color: #f4f7f6; color: #333; line-height: 1.6; margin: 0; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; margin-top: 0; }
        h2 { color: #2980b9; }
        form { display: flex; flex-direction: column; }
        input { padding: 10px; margin-bottom: 15px; border: 1px solid #ddd; border-radius: 4px; }
        button { background-color: #3498db; color: white; padding: 12px; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; transition: background 0.3s; }
        button:hover { background-color: #2980b9; }
        .success { color: #27ae60; background: #eafaf1; padding: 10px; border-radius: 4px; margin-bottom: 10px; }
        .error { color: #c0392b; background: #fdf2f2; padding: 10px; border-radius: 4px; margin-bottom: 10px; }
        .info { color: #3498db; background: #ebf5fb; padding: 10px; border-radius: 4px; margin-bottom: 10px; }
        a { color: #3498db; text-decoration: none; font-weight: bold; }
        a:hover { text-decoration: underline; }
        ul { padding-left: 20px; }
        li { margin-bottom: 5px; }
    </style>
</head>
<body>
<div class='container'>
    <h1>FulcrumOS Kurulum Sihirbazı</h1>
    <h2>$title</h2>";
}

function render_footer() {
    echo "    <div style='margin-top: 30px; font-size: 12px; color: #7f8c8d; text-align: center;'>
        &copy; " . date('Y') . " FulcrumOS - Tüm hakları saklıdır.
    </div>
</div>
</body>
</html>";
}

function check_server_requirements() {
    $checks = [];
    $checks['PHP Version (>= 8.1.0)'] = version_compare(PHP_VERSION, '8.1.0', '>=');
    $checks['PDO MySQL Extension'] = extension_loaded('pdo_mysql');
    $checks['OpenSSL Extension'] = extension_loaded('openssl');
    $checks['CURL Extension'] = extension_loaded('curl');
    $checks['SQL Schemas Readable'] = is_readable(__DIR__ . '/setup/sql/schema_auth.sql');

    echo "<ul>";
    $all_passed = true;
    foreach ($checks as $name => $passed) {
        $status = $passed ? "<span class='success' style='padding: 2px 5px;'>Tamam</span>" : "<span class='error' style='padding: 2px 5px;'>Hata</span>";
        echo "<li>$name: $status</li>";
        if (!$passed) $all_passed = false;
    }
    echo "</ul>";

    return $all_passed;
}

function write_config_files($db_host, $db_user, $db_pass, $db_prefix) {
    $jwt_secret = bin2hex(random_bytes(32));

    $env_content = "# Generated by FulcrumOS Installer on " . date('Y-m-d H:i:s') . "\n";
    $env_content .= "APP_ENV=production\n";
    $env_content .= "DB_HOST=$db_host\n";
    $env_content .= "DB_USER=$db_user\n";
    $env_content .= "DB_PASSWORD=$db_pass\n";
    $env_content .= "DB_ROOT_PASSWORD=$db_pass\n";

    $services = [
        'AUTH', 'ORGANIZASYON', 'KATALOG', 'ENVANTER', 'SIPARIS', 'IADE',
        'TEDARIK', 'RAPORLAMA', 'CMS', 'DESTEK', 'OTOMASYON', 'KUPON',
        'MEDYA', 'AI_ASISTAN', 'ENTEGRASYON', 'BILDIRIM'
    ];

    foreach ($services as $service) {
        $env_content .= "DB_NAME_$service={$db_prefix}" . strtolower($service) . "\n";
    }

    $env_content .= "JWT_SECRET_KEY=$jwt_secret\n";

    if (!empty($_POST['iyzico_key'])) $env_content .= "IYZICO_API_KEY=" . htmlspecialchars($_POST['iyzico_key']) . "\n";
    if (!empty($_POST['gemini_key'])) $env_content .= "GEMINI_API_KEY=" . htmlspecialchars($_POST['gemini_key']) . "\n";

    if (file_put_contents(__DIR__ . '/.env', $env_content)) {
        echo "<p class='success'>Sistem yapılandırma dosyası (.env) başarıyla oluşturuldu.</p>";

        // Admin-UI config
        $vite_url = "VITE_API_BASE_URL=http://localhost:8000\n";
        @mkdir(__DIR__ . '/servisler/admin-ui', 0755, true);
        file_put_contents(__DIR__ . '/servisler/admin-ui/.env.production', $vite_url);
        echo "<p class='success'>Admin-UI yapılandırması oluşturuldu.</p>";

        return true;
    } else {
        echo "<p class='error'>HATA: .env dosyası yazılamadı!</p>";
        return false;
    }
}

function create_databases_and_schemas($db_host, $db_user, $db_pass, $db_prefix) {
    $conn = @new mysqli($db_host, $db_user, $db_pass);
    if ($conn->connect_error) {
        echo "<p class='error'>Veritabanı Bağlantı Hatası: " . $conn->connect_error . "</p>";
        return false;
    }

    $services = [
        'auth', 'siparis', 'katalog', 'envanter', 'organizasyon', 'ai_asistan',
        'cms', 'destek', 'entegrasyon', 'iade', 'kupon', 'medya', 'otomasyon',
        'raporlama', 'tedarik', 'bildirim'
    ];

    foreach ($services as $service) {
        $db_name = $db_prefix . $service;
        if ($conn->query("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci")) {
            echo "<p class='info'>Veritabanı hazır: <b>$db_name</b></p>";

            $schema_file = __DIR__ . "/setup/sql/schema_$service.sql";
            if (file_exists($schema_file)) {
                $sql = file_get_contents($schema_file);
                if (!empty($sql)) {
                    $conn->select_db($db_name);
                    if ($conn->multi_query($sql)) {
                        do {
                            if ($result = $conn->store_result()) {
                                $result->free();
                            }
                        } while ($conn->more_results() && $conn->next_result());
                        echo "<p class='success'>Şema başarıyla yüklendi: $service</p>";
                    } else {
                        echo "<p class='error'>Şema yükleme hatası ($service): " . $conn->error . "</p>";
                    }
                }
            }
        } else {
            echo "<p class='error'>Veritabanı oluşturma hatası ($db_name): " . $conn->error . "</p>";
        }
    }
    $conn->close();
    return true;
}

function create_super_admin($db_host, $db_user, $db_pass, $db_prefix, $admin_email, $admin_pass) {
    $db_auth = $db_prefix . 'auth';
    $conn = @new mysqli($db_host, $db_user, $db_pass, $db_auth);
    if ($conn->connect_error) {
        echo "<p class='error'>Süper Admin oluşturulamadı (Bağlantı Hatası): " . $conn->connect_error . "</p>";
        return false;
    }

    $hashed_pass = password_hash($admin_pass, PASSWORD_DEFAULT);
    $stmt = $conn->prepare("INSERT INTO kullanicilar (ad_soyad, eposta, parola, rol_id, aktif_mi) VALUES (?, ?, ?, ?, ?)");
    $name = 'Süper Admin';
    $rol_id = 1; // super_admin
    $aktif_mi = 1;
    $stmt->bind_param("sssii", $name, $admin_email, $hashed_pass, $rol_id, $aktif_mi);

    if ($stmt->execute()) {
        echo "<p class='success'>Süper Admin hesabı başarıyla oluşturuldu: <b>$admin_email</b></p>";
        $stmt->close();

        // Tüm yetkileri super_admin rolüne ata
        $conn->query("INSERT IGNORE INTO rol_yetki_iliskisi (rol_id, yetki_id) SELECT 1, yetki_id FROM yetkiler");
        echo "<p class='info'>Süper Admin rolü yetkilendirildi.</p>";

        $conn->close();
        return true;
    } else {
        echo "<p class='error'>Süper Admin oluşturma hatası: " . $conn->error . "</p>";
        $stmt->close();
        $conn->close();
        return false;
    }
}

function seed_demo_data($db_host, $db_user, $db_pass, $db_prefix) {
    $demo_sql_file = __DIR__ . '/setup/sql/demo.sql';
    if (!file_exists($demo_sql_file)) {
        return true;
    }

    $sql = file_get_contents($demo_sql_file);
    if (trim($sql) === '') {
        echo "<p class='info'>Demo veri dosyası boş, atlanıyor.</p>";
        return true;
    }

    $conn = @new mysqli($db_host, $db_user, $db_pass);
    if ($conn->connect_error) {
        echo "<p class='error'>Demo veri yüklenemedi (Bağlantı Hatası).</p>";
        return false;
    }

    if ($conn->multi_query($sql)) {
        do {
            if ($result = $conn->store_result()) $result->free();
        } while ($conn->more_results() && $conn->next_result());
        echo "<p class='success'>Demo verileri başarıyla yüklendi.</p>";
    } else {
        echo "<p class='error'>Demo veri yükleme hatası: " . $conn->error . "</p>";
    }
    $conn->close();
    return true;
}

function lock_installer() {
    if (file_put_contents(__DIR__ . '/install.locked', 'Kurulum tamamlandı: ' . date('Y-m-d H:i:s'))) {
        echo "<p class='success'>Kurunlum sihirbazı güvenlik amacıyla kilitlendi (install.locked).</p>";
        return true;
    }
    return false;
}

// --- SİHİRBAZ ADIMLARI (HTML/FORM YÖNETİMİ) ---

switch ($step) {
    case 1:
        render_header("Adım 1: Sunucu Kontrolü");
        if (check_server_requirements()) {
            echo "<p>Sunucu gereksinimleri karşılanıyor.</p>";
            echo "<a href='?step=2'>İleri -></a>";
        } else {
            echo "<p>HATA: Sunucu gereksinimleri karşılanmıyor.</p>";
        }
        break;

    case 2:
        render_header("Adım 2: Veritabanı ve Admin Bilgileri");
        ?>
        <form action="?step=3" method="POST">
            <h3>Veritabanı Ayarları</h3>
            <input name="db_host" placeholder="Veritabanı Sunucusu" value="localhost" required>
            <input name="db_user" placeholder="Veritabanı Kullanıcısı" required>
            <input name="db_pass" placeholder="Veritabanı Şifresi" type="password">
            <input name="db_prefix" placeholder="Veritabanı Öneki (örn: fulcrumos_)" value="fulcrumos_">

            <h3>Süper Admin Kullanıcısı</h3>
            <input name="admin_email" placeholder="Admin E-posta" type="email" required>
            <input name="admin_pass" placeholder="Admin Şifresi" type="password" required>

            <h3>API Anahtarları (Opsiyonel)</h3>
            <input name="iyzico_key" placeholder="Iyzico API Key">
            <input name="gemini_key" placeholder="Gemini API Key">

            <h3>Demo Veri</h3>
            <label><input name="demo_data" type="checkbox" checked> Demo Verilerini Yükle (v9.1)</label>

            <button type="submit">Platformu Kur</button>
        </form>
        <?php
        break;

    case 3:
        render_header("Adım 3: Kurulum Yapılıyor...");

        if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
            echo "<p class='error'>HATA: Bu adıma doğrudan erişilemez.</p>";
            echo "<a href='?step=2'><- Geri Dön</a>";
            break;
        }

        $db_host = $_POST['db_host'] ?? 'localhost';
        $db_user = $_POST['db_user'] ?? '';
        $db_pass = $_POST['db_pass'] ?? '';
        $db_prefix = $_POST['db_prefix'] ?? 'fulcrumos_';
        $admin_email = $_POST['admin_email'] ?? '';
        $admin_pass = $_POST['admin_pass'] ?? '';
        $demo_data = isset($_POST['demo_data']);

        echo "<div class='info'>Kurulum işlemleri başlatıldı...</div>";

        $success = true;

        echo "<h3>1. Yapılandırma Dosyaları</h3>";
        if (!write_config_files($db_host, $db_user, $db_pass, $db_prefix)) $success = false;

        if ($success) {
            echo "<h3>2. Veritabanı ve Şemalar</h3>";
            if (!create_databases_and_schemas($db_host, $db_user, $db_pass, $db_prefix)) $success = false;
        }

        if ($success) {
            echo "<h3>3. Süper Admin Hesabı</h3>";
            if (!create_super_admin($db_host, $db_user, $db_pass, $db_prefix, $admin_email, $admin_pass)) $success = false;
        }

        if ($success && $demo_data) {
            echo "<h3>4. Demo Verileri</h3>";
            seed_demo_data($db_host, $db_user, $db_pass, $db_prefix);
        }

        if ($success) {
            echo "<h3>5. Güvenlik</h3>";
            lock_installer();

            echo "<div class='success' style='margin-top: 20px; padding: 20px;'>";
            echo "<h2>KURULUM BAŞARIYLA TAMAMLANDI!</h2>";
            echo "<p>FulcrumOS platformu kullanıma hazır.</p>";
            echo "<p><b>Admin E-posta:</b> $admin_email</p>";
            echo "<p>'admin-ui' (port 3000) üzerinden giriş yapabilirsiniz.</p>";
            echo "</div>";
        } else {
            echo "<div class='error' style='margin-top: 20px; padding: 20px;'>";
            echo "<h2>KURULUM BAŞARISIZ!</h2>";
            echo "<p>Lütfen yukarıdaki hataları giderip <a href='?step=2'>tekrar deneyin</a>.</p>";
            echo "</div>";
        }

        break;
}

render_footer();
